name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install root deps
        run: npm install
      - name: Install frontend deps
        run: npm --prefix frontend install
      - name: Lint and type-check
        run: npm run lint:ci
      - name: Build client
        run: npm run build:client
